apiVersion: v1
kind: Pod
metadata:
  name: good-pod
  namespace: dt-lab
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 10001
    seccompProfile: {type: RuntimeDefault}
  containers:
    - name: api
      image: ghcr.io/example/dt-orders-api:1.0.0
      securityContext:
        allowPrivilegeEscalation: false
        capabilities: {drop: ["ALL"]}
      resources:
        limits: {cpu: 500m, memory: 256Mi}
